---
sudo: required

services:
  - docker

env:
  - distro: ubuntu1604

before_install:
  - pip install ansible

script:
  - ansible --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
