---
sudo: required

language: python

before_install:
  - pip install -r requirements.txt

script:
  - ansible-playbook tasks/main.yml --syntax-check
  - ansible-playbook --sudo tasks/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
