---
sudo: required

services:
  - docker

env:
  - distro: ubuntu1604

before_install:
  - 'docker pull ansible/ansible:{distro}'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
