---
language: python

before_install:
  - pip install --upgrade ansible

script:
  - ansible-playbook --ask-pass tasks/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
