- name: Accept established connections.
  iptables: chain=INPUT ctstate=ESTABLISHED,RELATED jump=ACCEPT
  tags: iptables

- name: Accept localhost connections.
  iptables: chain=INPUT in_interface=lo jump=ACCEPT
  tags: iptables

- name: Accept ICMP packages.
  iptables: chain=INPUT protocol=icmp jump=ACCEPT
  tags: iptables

- name: Accept SSH connections.
  iptables: chain=INPUT protocol=tcp destination_port=22 jump=ACCEPT
  tags: iptables
- name: Accept HTTP connections.
  iptables: chain=INPUT protocol=tcp destination_port=80 jump=ACCEPT
  tags: iptables

- name: Accept HTTPS connections.
  iptables: chain=INPUT protocol=tcp destination_port=443 jump=ACCEPT
  tags: iptables

- name: Drop everything else.
  iptables: chain=INPUT jump=DROP
  tags: iptables
