---
- name: Install dependences
  package:
    name: software-properties-common
    state: latest
  tags: certbot

- name: Add APT repo
  apt_repository:
    repo: 'ppa:certbot/certbot'
    update_cache: yes
    codename: 'xenial'
  tags: certbot


- name: Install Certbot
  package:
    name: python-certbot-nginx
    state: latest
  tags: certbot
