---
# file: roles/base/tasks/iptables.yml

- name: Accept established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: Accept localhost connections
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  tags: iptables

- name: Accept ICMP packages
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  tags: iptables

- name: Accept known TCP protocols
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item  }}"
    jump: ACCEPT
  with_items:
    - 22
    - 80
    - 443
  tags: iptables

- name: Drop all other incoming connections
  iptables:
    chain: INPUT
    jump: DROP
  tags: iptables
